name: RedCraftChat
main: org.redcraft.redcraftchat.RedCraftChat
version: 0.1.0-SNAPSHOT
author: RedCraft
authors: [lululombard]
api-version: 1.19
permissions:
  redcraftchat.*:
    description: Gives access to all RedCraftChat permissions
    children:
      redcraftchat.formatting.*: true
      redcraftchat.command.*: true
      redcraftchat.command.*.others: true
      redcraftchat.moderation.*: true

  redcraftchat.formatting.*:
    description: Allows all kind of formatting
    children:
      redcraftchat.formatting.colors: true
      redcraftchat.formatting.styling: true
      redcraftchat.formatting.magic: true
  redcraftchat.formatting.colors:
    description: Allows color in chat
  redcraftchat.formatting.styling:
    description: Allows styling in chat
  redcraftchat.formatting.magic:
    description: Allows magic (&k) in chat

  redcraftchat.command.*:
    description: Allows access to all commands
    children:
      redcraftchat.command.player-settings: true
      redcraftchat.command.link-discord-account: true
      redcraftchat.command.lang: true
      redcraftchat.command.broadcast: true
      redcraftchat.command.me: true
  redcraftchat.command.*.others:
    description: Allows access to all commands as other player
    children:
      redcraftchat.command.player-settings.others: true
  redcraftchat.command.player-settings:
    description: Allows to use /player-settings to dump your own player settings
  redcraftchat.command.player-settings.others:
    description: Allows to use /player-settings to dump another player's settings
  redcraftchat.command.link-discord-account:
    description: Allows to use /discord-link to link your Discord account
  redcraftchat.command.lang:
    description: Allows to use /lang to choose your language
  redcraftchat.command.broadcast:
    description: Allows to use /broadcast to send an broadcast on Discord and Minecraft
  redcraftchat.command.me:
    description: Allows to use /me to send an action message
  redcraftchat.command.msg:
    description: Allows to use /msg to send private messages
  redcraftchat.command.mail:
    description: Allows to use /mail to send and receive mails

  redcraftchat.moderation.*:
    description: Allows access to all moderation tools
    children:
      redcraftchat.moderation.commandspy: true
      redcraftchat.moderation.commandspy.others: true
      redcraftchat.command.player-settings.others: true
  redcraftchat.moderation.commandspy:
    description: Allows to use /cspy
  redcraftchat.moderation.commandspy.others:
    description: Allows to toggle command spy for others
