package org.redcraft.redcraftchat.models.caching;

public enum CacheCategory {
    WEBHOOK_MESSAGE_MAPPING,
    USER_MESSAGE_MAPPING,
    DEEPL_TRANSLATED_MESSAGE,
    MODERNMT_TRANSLATED_MESSAGE,
    PLAYER_PREFERENCES,
    ACCOUNT_LINK_CODE_USER_ID,
    ACCOUNT_LINK_CODE,
    SUPPORTED_LOCALES,
}
